apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: suju
  name: suju
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suju
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: suju
    spec:
      containers:
      - image: rohit44docker/srst:v1
        name: srst
        resources: {}
status: {}
