apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-26T06:00:52Z"
  labels:
    app: spring
  name: spring
  namespace: default
  resourceVersion: "344785"
  uid: fea5bb0f-f201-4c66-a60c-dd0b423793bc
spec:
  clusterIP: 10.110.56.51
  clusterIPs:
  - 10.110.56.51
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: spring
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
